---
- name: Create node-exporter directory
  ansible.builtin.file:
    path: "{{ node_exporter_dir }}"
    state: directory
    mode: "0755"

- name: Copy compose file
  ansible.builtin.copy:
    src: compose.yml
    dest: "{{ node_exporter_dir }}/compose.yml"
    mode: "0644"

- name: Deploy node-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ node_exporter_dir }}"
    state: present
    pull: always
