---
services:
  k6:
    image: grafana/k6
    command: >
      run
      --out experimental-prometheus-rw
      --out "json=/data/output/output.json"
      /data/tests/login.js
    volumes:
      - ./outputs:/data/output
      - ./tests:/data/tests
    environment:
      K6_PROMETHEUS_RW_SERVER_URL: ${HOSTNAME_METRICS}/api/v1/write
      K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM: true
      K6_PROMETHEUS_RW_PUSH_INTERVAL: 1s
      BENCH_HOST: ${BENCH_HOST:?authentik host required}
      BENCH_PORT: ${BENCH_PORT:-9000}
      VUS: ${VUS:-8}
      FLOW_NO_MFA: ${FLOW_NO_MFA}
      FLOW_WITH_MFA: ${FLOW_WITH_MFA}
